# $ micromamba create -f environment.yml
# $ micromamba activate trnsprtProp
#

name: trnsprtProp
channels:
  - conda-forge
dependencies:
  - python==3.10
  - ase
  - numpy
  - scipy
  - moltemplate
  - matplotlib
  - ipython
  - pandas 
  - statsmodels
  - ipykernel 
  # Packaging
  - flit
  - pytest==6.2.5
  - coverage==6.1.1
  - pytest-cov==3.0.0
  - flake8==3.9.2
  - mypy==0.910
  - black==21.10b0
  - isort==5.9.3
  - autoflake==1.4
  - flake8-docstrings==1.6.0
