name: CI

on: [push, pull_request]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    name: test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build-type: [Release]

    steps:
    - uses: actions/checkout@v4

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.5.7-0'
        environment-file: environment.yml
        init-shell: bash
        cache-environment: true
        post-cleanup: 'all'

    - name: Test with pytest
      shell: micromamba-shell {0}
      run: |
        pip install .
        pytest -v