# Options for calculating the solvation time correlation function
# Comment out if you want to use default values
# Two log file will be required, each containing the energy gap calculated
# for every time step 
[tcf]
log_ground_state = '2-groundState/logfile/log-groundState.txt'

# Second logfile, in the excited state (but the same configurations)
log_excited_state = '1-excitedState/logfile/log-excitedState.txt'

# Key string corresponding to the energy gap (compute) value
# in the LAMMPS log files.  
energy_gap_key_string = 'c_solEnerg[0]'

# Key string corresponding to the timestep value
# in the LAMMPS log files. By default it is set to "Step"
# timestep_key_string = 'Step'

# The maximum lag time that will be calculated. 
# By default, this is int(0.5* total number of steps)
# max_lag_time =

# A first time origin of 0 corresponds to the first configuration
# in the trajectory file 
first_time_origin = 0

# The first lag time to calculate 
first_lag_time = 1

# Step size in the lag times. By default it is 1. 
# Comment out to use the default value 
step_size_lag_time = 1